version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      # Options: "daily", "weekly", "monthly"
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "gradle"